name: CI

on:
  push:
    branches:
      - main

env: DATABASE_URL = "https://example.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript typechecking
        run: npm run typecheck

      - name: Run ESLint
        run: npm run lint
